### PR TITLE
Fixed #173

### LINKED ISSUE #173: Wrong link in svg
Link in SVG for loadout with revision always points to the page of the latest revision

### PR DESCRIPTION
**Pull request by unti1x**
Fixed link to point to revision

### CODE REVIEW

**Comment by Artefact2** [comment]
Thanks for the (simple) fix. Add your name to the copyright header & I can merge this. Also, please don't reference issue numbers in commit messages (use a more descriptive commit name).

**Comment by unti1x** [comment]
I don't think this fix is enough to add my name to copyright. =D 

Actually, issue reference is a common practice in github, 'couse it allows you to close issues with pr (https://github.com/blog/1506-closing-issues-via-pull-requests)

**Comment by Artefact2** [comment]
> I don't think this fix is enough to add my name to copyright. =D

Copyright is tricky, I don't want to take any potential risks.

> Actually, issue reference is a common practice in github, 'couse it allows you to close issues with pr 

If the project ever moves away from github (or someone wants to fork or host a mirror somewhere else, or someone just uses `git log`) all context will be lost and you'll be left with a bunch of useless commit messages.

Sorry if I sound rude, I really enjoy you taking the time to contribute.

**Comment by unti1x** [comment]
Got it. Gonna fix these as soon as possible

**Comment by unti1x** [comment]
Done. Let me know if I have to change anything else.

**Comment by Artefact2** [comment]
Cherry-picked into v0.13.5-hotfixes as 4160b22b5a8a84b8c79b02ab27ba2d9dcebacc95.

**Pull request closed without merging**
